@startuml
left to right direction
actor User

rectangle HotelManagementSystem {
    usecase "Make Reservation" as UC1
    usecase "Display Rooms" as UC2
    usecase "Display Reservations" as UC3

    User --> UC1
    User --> UC2
    User --> UC3

}
@enduml